services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: secure_demo
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
